services:
# ------------------- Base de donnees Postgress ---------------
    db:
      image: postgres:15
      container_name: retentionAI_db
      restart: always
      environment: 
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password1234
        POSTGRES_DB: RetentionAI
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5
      networks:
      - app-RetentionAI-network
# ----------------- backend fastApi ------------
    backend:
      build: .
      container_name: retentionAI_backend
      ports:
        - "8000:8000"
      env_file:
        - ./.env.docker
      depends_on:
          db:
            condition: service_healthy # Le backend démarre uniquement quand PostgreSQL est prêt
      networks:
          - app-RetentionAI-network
# ------------------- Frontend Next.js -----------------
    frontend:
      build: ../retentionai-frontend
      container_name: retentionAI_frontend
      ports:
        - "3000:3000"
      depends_on:
        - backend
      networks:
      - app-RetentionAI-network

volumes:
  postgres_data:

networks:
  app-RetentionAI-network:
    driver: bridge  # privé partagé par les 3 services.